version: "3"
services:
  #   server:
  #     build:
  #       context: .
  #       dockerfile: .docker/server/Dockerfile
  #     ports:
  #       - "5000:5000"
  #     depends_on:
  #       - db
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "1234asdfFDSA@2019"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
